### ISSUE TITLE
Animation failed with error when debugInfoEnabled(false)

### ISSUE THREAD

**Issue by se-panfilov** [homerjam/angular-ui-router-anim-in-out#8]
I want to prepare my app for production according to this doc: https://docs.angularjs.org/guide/production

But after this step

```javascript
myApp.config(['$compileProvider', function ($compileProvider) {
  $compileProvider.debugInfoEnabled(false);
}]);
```

An anim-in-out.js will throw an error:

```javascript
TypeError: Cannot read property '$broadcast' of undefined
    at Object.leave [as fn] (anim-in-out.js)
    at angular-animate.js:745
    at s (angular.js:323)
    at k (angular-animate.js:727)
    at Object.f.module.directive.factory.config.X.decorator.before (angular-animate.js:768)
    at G (angular-animate.js:1411)
    at angular-animate.js:1001
    at angular-animate.js:539
    at l.$get.l.$digest (angular.js:14293)
    at l.$get.l.$apply (angular.js:14506)
 (anonymous function)
$getangular.js
$get.l.$digestangular.js
$get.l.$applyangular.js
(anonymous function)
```

**Comment by homerjam** [comment]
Cool! I didn't even know about this!

This is strange. Either the directive is unable to access `$rootScope` or the scope of the element - this might be because the `.scope()` method is disabled with the debug info as is suggested by the docs. I've updated the file with a couple of `console.log`s to see whats happening - can you try [this version](https://raw.githubusercontent.com/homerjam/angular-ui-router-anim-in-out/debug-disabled/anim-in-out.js) and let me know what happens.

Or better still could you make an isolated example in jsfiddle/plunkr - maybe using the demo as a base?

Thanks

**Comment by homerjam** [comment]
I've removed the reliance on angular.element().scope() which was causing this error
